src/config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  devise_for :users
  get 'users/index' => 'users#index', as: 'users_path'
  get 'users/list' => 'users#list', as: 'list_movie_user'
  get 'movies/:id/borrow' => 'movies#borrow', as: 'borrow_movie'
  get 'users/:id/return' => 'users#return', as: 'return_movie'
  get 'users/profile' => 'users#show', as: 'show_user'
  resources :categories
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users
end

src/app/models/movie.rb
class Movie < ApplicationRecord
  has_and_belongs_to_many :categories;
  has_and_belongs_to_many :users
end

src/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :category_list, only: [:new, :edit, :show]
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    if current_user.has_role? :admin 
      respond_to do |format|
        if @movie.update(movie_params)
          format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
          format.json { render :show, status: :ok, location: @movie }
        else
          format.html { render :edit }
          format.json { render json: @movie.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back
    end 
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def borrow
    @movie = Movie.find(params[:id])
    @userMovie = Movie.joins(:users).where("users.id = ? AND movie_id = ?", current_user.id, @movie.id)

    if @movie.quantity > 0
      if @userMovie.empty?
        @movie.quantity -= 1
        
        @movie.update(quantity: @movie.quantity)
        @movie_user = MoviesUser.create(movie_id: @movie.id, user_id: current_user.id)
        @movie_user.save

        respond_to do |format|
          format.html { redirect_to movies_path, notice: 'The movie "' + @movie.title + '" was successfully borrowed' }
        end
      else
        respond_to do |format|
          format.html { redirect_to movies_path, notice: 'You already have the movie "' + @movie.title + '" in your list' }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to movies_path, notice: 'There is no more copy of the movie "' + @movie.title + '"' }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description, :duree, :quantity, category_ids: [])
    end

    def category_list
      @categories = Category.all
    end
end

src/app/helpers/movies_helper.rb
module MoviesHelper
  def movie_categories_label(categories)
    raw categories.map  {|cat| "<span style='color:#{cat.color}'>#{cat.name}</span>" } .join(', ')
  end
end

src/app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="card col-12">
        <div class="row">
          <div class="col-6">
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title %>
            </div>
            <div class="field">
              <%= form.label :description %>
              <%= form.text_area :description %>
            </div>
            <div class="field">
              <%= form.label :duree %>
              <%= form.number_field :duree %>
            </div>
            <div class="field">
              <%= form.label :borrowed %>
              <%= form.number_field :quantity %>
            </div>
          </div>
          <div class="col-6">
            <div class="field">
              <%= form.label :category_ids %>
              <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) %>
            </div>
          </div>
        </div>
        <div class="actions">
          <%= form.submit %>
        </div>
      </div>
    </div>
  </div>
<% end %>

src/app/views/movies/edit.html.erb
<% if current_user.has_role? :admin %>
  <div class="container">
    <div class="row">
      <h1>Editing Movie</h1>
    </div>
  </div>
  <%= render 'form', movie: @movie %>

  <div class="container">
    <div class="row">
      <div class="col-1">
        <%= link_to 'Show', @movie %>
      </div>
      <div class="col-1">
        <%= link_to 'Back', movies_path %>
      </div>
    </div>
  </div>

<% else %>

  <p> Non autorisé <p>

<% end %>

src/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <% if user_signed_in? %>
    Compte connecté : <%= current_user.email %>
    <%= link_to("Mon profil", show_user_path(current_user.id)) %>
    <% if current_user.has_role? :admin %>
      <%= link_to("Membres", users_path_url) %>
      <%= link_to("Catégories", categories_path) %>
    <% end %>
    <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
    </br>
    <%= link_to('Inscription', new_user_registration_path) %>
  <% end %>
  <h1>Tous les films</h1>
  <div class="row justify-content-center">
    <% @movies.each do |movie| %>
      <div class="card col-3" style="margin: 15px;">
        <div>
          <h3> <%= movie.title %> </h3>
          <p> <%= movie.description %> </p>
          <p> <%= movie.duree %> minutes</p>
          <p> <%= movie_categories_label(movie.categories) %> </p>
          <p> <%= movie.quantity %> <%= movie.quantity > 1 ? 'exemplaires' : 'exemplaire' %> de disponible </p>
          <% if movie.quantity > 0 %>
            <%= link_to 'Emprunter', borrow_movie_path(movie) %>
          <% end %>
          <%= link_to 'Show', movie %>
          <% if current_user.has_role? :admin %>
            <%= link_to 'Edit', edit_movie_path(movie) %>
            <%= link_to 'Destroy', movie, method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <% if current_user.has_role? :admin %>
    <h2><%= link_to 'New Movie', new_movie_path %></h2>
  <% end %>
  <h3><%= link_to 'Ma liste de films', list_movie_user_path %></h3>
</div>

src/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

src/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="card col-12">
      <p>
        <strong>Title:</strong>
        <%= @movie.title %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @movie.description %>
      </p>

      <p>
        <strong>Duree:</strong>
        <%= @movie.duree %> minutes
      </p>

      <p>
        <strong>Genre:</strong>
        <%= movie_categories_label(@movie.categories) %>
      </p>

      <p>
        <strong>Borrowed:</strong>
        <%= @movie.quantity %> <%= @movie.quantity > 1 ? 'exemplaires': 'exemplaire' %> de disponible
      </p>
      <div class="row">
        <div class="col-1">
          <% if current_user.has_role? :admin %>
            <%= link_to 'Edit', edit_movie_path(@movie) %>
          <% end %>
        </div>
        <div class="col-1">
          <%= link_to 'Back', movies_path %>
        </div>
      </div>
    </div>
  </div>
</div>