src/config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  devise_for :users
  get 'users/index' => 'users#index', as: 'users_path'
  get 'users/list' => 'users#list', as: 'list_movie_user'
  get 'movies/:id/borrow' => 'movies#borrow', as: 'borrow_movie'
  get 'users/:id/return' => 'users#return', as: 'return_movie'
  get 'users/profile' => 'users#show', as: 'show_user'
  resources :categories
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users
end

src/app/models/user.rb
class User < ApplicationRecord
	after_create :assign_default_role
  	rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	def assign_default_role
		self.add_role(:normal) if self.roles.blank?
	end
  has_and_belongs_to_many :movies
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :confirm_signed_in
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def list
    #récupère les films qui appartiennent au user
    @movies = Movie.joins(:users).where("users.id = ?", current_user.id)
  end

  def show
    @user = User.find(current_user.id)
  end


  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def return
    @movie = Movie.find(params[:id])

    @movie.quantity += 1
    @movie.update(quantity: @movie.quantity)

    @movie_user = MoviesUser.where("movie_id = ? AND user_id = ?", @movie.id, current_user.id).first
    MoviesUser.delete(movie_id: @movie.id, user_id: current_user.id)

    respond_to do |format|
      format.html { redirect_to list_movie_user_path, notice: 'The movie "' + @movie.title + '" was successfully returned' }
    end
  end

  private

  def confirm_signed_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :name, :firstname)
  end

end

src/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="card col-12">
        <div class="row">
          <div class="col-6">
            <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email %>
              </div>
              <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name %>
              </div>
              <div class="field">
                <%= form.label :firstname %>
                <%= form.text_area :firstname %>
              </div>
          </div>
        </div>
        <div class="actions">
          <%= form.submit %>
        </div>
      </div>
    </div>
  </div>
<% end %>

src/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Editing User</h1>
  </div>
</div>
<% if current_user.has_role? :admin %>
  <%= render 'form', user: @user %>
<% else %>
  <%= render 'form', user: current_user %>
<% end %>



<div class="container">
  <div class="row">
    <div class="col-1">
      <% if current_user.has_role? :admin %>
        <%= link_to("back", users_path_url) %>
      <% else %>
        <%= link_to("back", show_user_path(current_user.id)) %>
      <% end %>
    </div>
  </div>
</div>

src/app/views/users/index.html.erb
<h1>Tous les utilisateurs</h1>
  <div class="row justify-content-start">
      <% @users.each do |user| %>
        <div class="card col-3" style="margin: 15px;">
          <p><%= user.email %></p>
          <% if user.has_role? :admin %>
            <p>Role = admin</p>
          <% elsif user.has_role? :normal %>
            <p>Role = normal</p>
          <% else %>
            <p>Role = none</p>
          <% end %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      <% end %>  
  </div>

  <div class="container">
  <div class="row">
    <div class="col-1">
      <%= link_to 'Back', movies_path %>
    </div>
  </div>
</div>

src/app/views/users/list.html.erb
<p><%= notice %></p>
<div class="container">
  <div class="row">
    <h1>Ma liste de films</h1>
  </div>

  <div class="row">
    <div class="col-6">
      <table class="table">
        <thead>
          <th scope="col">Titre</th>
          <th scope="col">Description</th>
          <th scope="col">Durée</th>
          <th></th>
        </thead>
        <tbody>
          <% @movies.each do |movie| %>
          
            <tr>
              <td><%= movie.title %></td>
              <td><%= movie.description %></td>
              <td><%= movie.duree %></td>
              <td><%= link_to 'Rendre', return_movie_path(movie) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <h3><%= link_to("Liste des films", movies_path) %></h3>
</div>

src/app/views/users/show.html.erb
<h1>Profil</h1>
<div class="card col-3" style="margin: 15px;">
	<p>Email : <%= @user.email %></p>
	<p>Nom : <%= @user.name %></p>
	<p>Prenom :<%= @user.firstname %></p>
</div>

<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', movies_path %>