src/config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  devise_for :users
  get 'users/index' => 'users#index', as: 'users_path'
  get 'users/list' => 'users#list', as: 'list_movie_user'
  get 'movies/:id/borrow' => 'movies#borrow', as: 'borrow_movie'
  get 'users/:id/return' => 'users#return', as: 'return_movie'
  get 'users/profile' => 'users#show', as: 'show_user'
  resources :categories
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users
end

src/app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  validates :content, length:  {minimum: 10}
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :category_list, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :create]

  #GET /posts
  def index
    @posts = Post.all
  end

  #GET /posts/1
  def show
    # before action
  end

  #GET /posts/new
  def new
    @post = Post.new
  end

  #POST /posts
  def create
    @post = Post.new post_params
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  #GET /posts/1/edit
  def edit
    # before action
  end

  #
  def update
    # before action
    if @post.update post_params
      redirect_to @post, notice: "Post updated"
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    # before action
    @post.destroy
    redirect_to posts_url, notice: "Post destroyed"
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find params[:id]
  end

end

src/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form|%>
  <% if post.errors.any? %>
    <div>
      <h2>There is <%= pluralize post.errors.count, 'error' %></h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

src/app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<%= render 'form', post: @post %>

<%= link_to("Listes d'articles", posts_path) %>

src/app/views/posts/index.html.erb
<p> <%= notice %> </p>



<p>
  <% if user_signed_in? %>
    Compte connecté : <%= current_user.email %>
    <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
  </br>
    <%= link_to('Inscription', new_user_registration_path) %>
  <% end %>
</p>


<h1> Posts </h1>

<table>
  <thead>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3">Actions</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to("Show", post) %></td>
        <td><%= link_to("Edit", edit_post_path(post)) %></td>
        <td><%= link_to("Destroy", post, method: :delete, data: {confirm: "Supprimer ?"}) %>></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to("New Posts", new_post_path) %>

src/app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render 'form', post: @post %>

<%= link_to("Listes d'articles", posts_path) %>

src/app/views/posts/show.html.erb
<p><%= notice %></p>

<p> Title : <%= @post.title %></p>
<p> Content : <%= @post.content %></p>

<%= link_to("Listes d'articles", posts_path) %>